# -*- coding: utf-8 -*-
"""Module 2 Project - Exploratory Data Analysis on Melbourne Housing.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10RGMeyog2MOv-hncl_QYan_WR11Vjp2k
"""

import pandas as pd
df = pd.read_csv('/content/housing.csv')
import matplotlib.pyplot as plt
df.head()

# Create the scatter plot, coloring by 'category'
colors = ['#AA544A', '#24ACD3', '#FFC300', '#6A0572', '#FF5733']

unique_types = df['Type'].unique()
type_color_map = dict(zip(unique_types, colors))
plt.scatter(df['Landsize'], df['Price'], c=df['Type'].astype('category').cat.codes)

type_codes = df['Type'].astype('category').cat.codes.unique()
for type_name in unique_types:
    df_type = df[df['Type'] == type_name]
    color_code = type_color_map[type_name]
    plt.scatter(df_type['Landsize'], df_type['Price'], c=[color_code] * len(df_type), label=type_name)

plt.xlabel('Landsize')
plt.ylabel('Price')
plt.title('Scatter Plot Colored by Category')
plt.legend(title='Property Type')

plt.show()

average_price_per_year = df.groupby('YearBuilt')['Price'].mean().reset_index()
average_price_per_year = average_price_per_year.sort_values('YearBuilt')
plt.figure(figsize=(12, 6))
plt.plot(average_price_per_year['YearBuilt'], average_price_per_year['Price'])

plt.xlabel('YearBuilt')
plt.ylabel('Price')
plt.title('Line Plot Average Price per Year')


plt.show()

average_price = df.groupby('Regionname')['Price'].mean().reset_index()
average_price = average_price.sort_values('Regionname')
plt.figure(figsize=(18, 6))
plt.bar(average_price['Regionname'], average_price['Price'])

plt.xlabel('Region Name')
plt.ylabel('Price')
plt.title('Bar Average Price Region')
plt.xticks(rotation=90)

plt.show()

plt.hist(df['Price'], bins=30)
plt.xlabel('Price')
plt.ylabel('Frequency')
plt.title('Histogram of Price')
plt.show()

grouped_data = [df[df['Regionname'] == region]['YearBuilt'].dropna().values for region in df['Regionname'].unique()]
region_names = df['Regionname'].unique()

plt.figure(figsize=(18, 6))
plt.boxplot(grouped_data, tick_labels=region_names, orientation='horizontal')

plt.xlabel('Year Built')
plt.ylabel('Region Name')
plt.title('Box Plot of Year Built by Region')
plt.xticks(rotation=90)

plt.show()

df.info()